# Run as commit-hook instead
rubocop:
  enabled: false
java_script:
  config_file: .javascript-style.json
  exclude:
    -"app/assets/javascripts/app.js"
    -"app/assets/javascripts/markdown.js"
scss:
  config_file: .scss-lint.yml
  exclude:
    -"app/assets/stylesheets/mixins.scss"
    -"app/assets/stylesheets/plugins/*"
