require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ExLinksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ExLink. As you add validations to ExLink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExLinksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all ex_links as @ex_links" do
      ex_link = ExLink.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ex_links)).to eq([ex_link])
    end
  end

  describe "GET #show" do
    it "assigns the requested ex_link as @ex_link" do
      ex_link = ExLink.create! valid_attributes
      get :show, {:id => ex_link.to_param}, valid_session
      expect(assigns(:ex_link)).to eq(ex_link)
    end
  end

  describe "GET #new" do
    it "assigns a new ex_link as @ex_link" do
      get :new, {}, valid_session
      expect(assigns(:ex_link)).to be_a_new(ExLink)
    end
  end

  describe "GET #edit" do
    it "assigns the requested ex_link as @ex_link" do
      ex_link = ExLink.create! valid_attributes
      get :edit, {:id => ex_link.to_param}, valid_session
      expect(assigns(:ex_link)).to eq(ex_link)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ExLink" do
        expect {
          post :create, {:ex_link => valid_attributes}, valid_session
        }.to change(ExLink, :count).by(1)
      end

      it "assigns a newly created ex_link as @ex_link" do
        post :create, {:ex_link => valid_attributes}, valid_session
        expect(assigns(:ex_link)).to be_a(ExLink)
        expect(assigns(:ex_link)).to be_persisted
      end

      it "redirects to the created ex_link" do
        post :create, {:ex_link => valid_attributes}, valid_session
        expect(response).to redirect_to(ExLink.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved ex_link as @ex_link" do
        post :create, {:ex_link => invalid_attributes}, valid_session
        expect(assigns(:ex_link)).to be_a_new(ExLink)
      end

      it "re-renders the 'new' template" do
        post :create, {:ex_link => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ex_link" do
        ex_link = ExLink.create! valid_attributes
        put :update, {:id => ex_link.to_param, :ex_link => new_attributes}, valid_session
        ex_link.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ex_link as @ex_link" do
        ex_link = ExLink.create! valid_attributes
        put :update, {:id => ex_link.to_param, :ex_link => valid_attributes}, valid_session
        expect(assigns(:ex_link)).to eq(ex_link)
      end

      it "redirects to the ex_link" do
        ex_link = ExLink.create! valid_attributes
        put :update, {:id => ex_link.to_param, :ex_link => valid_attributes}, valid_session
        expect(response).to redirect_to(ex_link)
      end
    end

    context "with invalid params" do
      it "assigns the ex_link as @ex_link" do
        ex_link = ExLink.create! valid_attributes
        put :update, {:id => ex_link.to_param, :ex_link => invalid_attributes}, valid_session
        expect(assigns(:ex_link)).to eq(ex_link)
      end

      it "re-renders the 'edit' template" do
        ex_link = ExLink.create! valid_attributes
        put :update, {:id => ex_link.to_param, :ex_link => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested ex_link" do
      ex_link = ExLink.create! valid_attributes
      expect {
        delete :destroy, {:id => ex_link.to_param}, valid_session
      }.to change(ExLink, :count).by(-1)
    end

    it "redirects to the ex_links list" do
      ex_link = ExLink.create! valid_attributes
      delete :destroy, {:id => ex_link.to_param}, valid_session
      expect(response).to redirect_to(ex_links_url)
    end
  end

end
